name: Test Create Repo

on:
  workflow_dispatch:
    inputs:
        myName:
          description: 'A random name'
          default: 'Guide'
          required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: ${{ inputs.myName }}
      TOKEN: ${{ secrets.TOKEN }}
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        run: |
            curl -sSL https://install.python-poetry.org | python3 -
            echo "$HOME/.poetry/bin" >> $GITHUB_PATH
            poetry --version
  
      - name: Install project dependencies
        run: poetry install

      - name: Run Python Script
        run: |
            poetry run python create_repo.py